name: limo # you probably want to 'snapcraft register <name>'
version: '0.0.3.20210803' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Linux system resources monitor. # 79 char long summary
description: |
  A simple Linux system resources monitor, created by Joker2770< https://github.com/Joker2770/limo >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  limo:
    command: limo
    extensions: [gnome-3-28]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - unity7
      - x11

parts:
  limo:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/Joker2770/limo.git
    source-type: git
    source-branch: main
    source-depth: 1
    # source: ../
    artifacts: [limo]
    build-packages:
      - gcc
      - make
      - libgtk-3-dev
  
    stage-packages:
      - libgtk-3-0

