name: limo # you probably want to 'snapcraft register <name>'
version: '0.0.1.20210725' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Linux system resources monitor. # 79 char long summary
description: |
  A simple Linux system resources monitor, create by Joker2770< https://github.com/Joker2770/limo >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20

apps:
  limo:
    command: limo
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7

parts:
  limo:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/Joker2770/limo.git
    source-type: git
    source-branch: main
    source-depth: 1
    # source: ../
    # artifacts: [limo]
    build-packages:
      - gcc
      - make
      - libgtk-3-dev
  
    stage-packages:
      - libgtk-3-0

    # build-environment:
      # - GDK_PIXBUF_MODULE_FILE: /snap/gnome-3-38-2004-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-current/loaders.cache


