name: limo # you probably want to 'snapcraft register <name>'
version: '0_0_1_20210725' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Linux system resources monitor.# 79 char long summary
description: |
  A simple Linux system resources monitor, create by Joker2770< https://github.com/Joker2770/limo >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  limo:
    command: limo

parts:
  limo:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/Joker2770/limo.git
    source-type: git
    source-branch: master
    source-depth: 1
    # source: ../
    artifacts: [limo]
    build-packages:
      - gcc
      - make
      - libgtk-3-dev
  
    stage-packages:
      - libgtk-3-0
      

